# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170327_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.MenuCategory'),
        ),
    ]
