# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_menuitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermenuitem',
            old_name='remove_ingredient',
            new_name='remove_ingredients',
        ),
    ]
