# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-11 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170403_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='party_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PartyMember'),
        ),
    ]
