# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-11 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170411_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='table',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Table'),
        ),
    ]
