# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-12 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170411_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermenuitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
