# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-12 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20170412_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.TableMap'),
        ),
    ]
