# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-13 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_table_table_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablemap',
            name='height',
            field=models.PositiveSmallIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='tablemap',
            name='width',
            field=models.PositiveSmallIntegerField(default=1000),
        ),
    ]
