# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-15 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20170413_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.SlugField(default='A', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='color',
            field=models.IntegerField(default=16777215),
        ),
        migrations.AlterField(
            model_name='table',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='table',
            name='width',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='table',
            name='x_coord',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='table',
            name='y_coord',
            field=models.IntegerField(default=50),
        ),
    ]
