# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-16 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20170416_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='current_party',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_table', to='api.Party'),
        ),
    ]
