# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-17 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_table_current_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
